# Generated by Django 5.2.15 on 2026-06-05 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=30, unique=True)),
                ('color_hex', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'цвет',
                'verbose_name_plural': 'цвета',
                'db_table': 'plant"."dict_colors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_id', models.AutoField(primary_key=True, serialize=False)),
                ('family_rus', models.CharField(max_length=50, unique=True, verbose_name='семейство (рус)')),
                ('family_lat', models.CharField(max_length=50, unique=True, verbose_name='семейство (лат)')),
            ],
            options={
                'verbose_name': 'семейство',
                'verbose_name_plural': 'семейства',
                'db_table': 'plant"."plant_families',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='род (лат)')),
                ('rus_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='род (рус)')),
            ],
            options={
                'verbose_name': 'род',
                'verbose_name_plural': 'роды',
                'db_table': 'plant"."genera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'месяц',
                'verbose_name_plural': 'месяцы',
                'db_table': 'plant_info"."dict_months',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id_plant', models.AutoField(primary_key=True, serialize=False)),
                ('variety', models.CharField(blank=True, max_length=100, null=True, verbose_name='сорт')),
                ('lat_name_unique', models.CharField(blank=True, max_length=100, null=True, verbose_name='латинское название')),
                ('url_slug', models.CharField(blank=True, max_length=100, null=True)),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='русское название')),
                ('rus_name_unique', models.CharField(blank=True, max_length=100, null=True)),
                ('id_pp', models.IntegerField(blank=True, null=True, verbose_name='ключ донорских фото')),
                ('usda_zone', models.IntegerField(blank=True, null=True, verbose_name='зона USDA')),
                ('is_template', models.BooleanField(default=False, verbose_name='шаблон вида')),
                ('is_ishs_registered', models.BooleanField(default=False, null=True, verbose_name='зарегистрирован ISHS')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'растение',
                'verbose_name_plural': 'растения',
                'db_table': 'plant"."plants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.TextField(blank=True, null=True)),
                ('public_url', models.TextField()),
                ('preview_url', models.TextField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, default='donor', max_length=50, null=True)),
                ('is_main', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
                'db_table': 'media"."plant_photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlantSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym_name', models.CharField(max_length=50)),
                ('is_binomial', models.BooleanField(default=False)),
                ('synonym_lang', models.CharField(blank=True, choices=[('Русский', 'Русский'), ('Латинский', 'Латинский'), ('Оригинальный', 'Оригинальный')], max_length=20, null=True)),
                ('synonym_type', models.CharField(blank=True, choices=[('Альтернативное', 'Альтернативное'), ('Перевод', 'Перевод'), ('Транслит', 'Транслит'), ('Народное', 'Народное'), ('Устаревшее', 'Устаревшее'), ('Торговое', 'Торговое')], max_length=20, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'синоним',
                'verbose_name_plural': 'синонимы',
                'db_table': 'plant"."plant_synonyms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='вид (лат)')),
                ('rus_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='вид (рус)')),
            ],
            options={
                'verbose_name': 'вид',
                'verbose_name_plural': 'виды',
                'db_table': 'plant"."species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlantCare',
            fields=[
                ('plant', models.OneToOneField(db_column='id_plant', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='care', serialize=False, to='catalog.plant')),
                ('sun', models.JSONField(blank=True, default=list, null=True)),
                ('soil_acid', models.JSONField(blank=True, default=list, null=True)),
                ('soil_demanding', models.BooleanField(default=False, null=True)),
                ('propagation', models.JSONField(blank=True, default=list, null=True)),
                ('care_level', models.JSONField(blank=True, default=list, null=True)),
                ('care_city', models.BooleanField(default=False, null=True)),
                ('care_disease_resistant', models.BooleanField(default=False, null=True)),
                ('care_pest_resistant', models.BooleanField(default=False, null=True)),
                ('care_no_shelter_boolean', models.BooleanField(default=False, null=True)),
                ('care_no_digging_boolean', models.BooleanField(default=False, null=True)),
                ('care_no_watering_boolean', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'характеристики (уход)',
                'verbose_name_plural': 'характеристики (уход)',
                'db_table': 'plant_info"."plant_care',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlantDescription',
            fields=[
                ('plant', models.OneToOneField(db_column='id_plant', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='description', serialize=False, to='catalog.plant')),
                ('content_text', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('problems', models.TextField(blank=True, null=True)),
                ('diseases_pests', models.TextField(blank=True, null=True)),
                ('propagation', models.TextField(blank=True, null=True)),
                ('usage_info', models.TextField(blank=True, null=True)),
                ('interesting_facts', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'описание',
                'verbose_name_plural': 'описания',
                'db_table': 'plant_info"."plant_descriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlantDesign',
            fields=[
                ('plant', models.OneToOneField(db_column='id_plant', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='design', serialize=False, to='catalog.plant')),
                ('design_uses', models.JSONField(blank=True, default=list, null=True)),
                ('garden_styles', models.JSONField(blank=True, default=list, null=True)),
                ('designer', models.JSONField(blank=True, default=list, null=True)),
                ('fruit_uses', models.JSONField(blank=True, default=list, null=True)),
                ('fruiting_months', models.JSONField(blank=True, null=True)),
                ('is_toxic', models.BooleanField(default=False, null=True)),
                ('has_aroma', models.BooleanField(default=False, null=True)),
                ('is_self_fertile', models.BooleanField(default=False, null=True)),
                ('is_allergen', models.BooleanField(default=False, null=True)),
                ('has_decorative_bark', models.BooleanField(default=False, null=True)),
                ('has_decorative_fruit', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'характеристики (дизайн)',
                'verbose_name_plural': 'характеристики (дизайн)',
                'db_table': 'plant_info"."plant_design',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlantVisual',
            fields=[
                ('plant', models.OneToOneField(db_column='id_plant', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='visual', serialize=False, to='catalog.plant')),
                ('height_max_cm', models.IntegerField(blank=True, null=True)),
                ('diameter_max_cm', models.IntegerField(blank=True, null=True)),
                ('annual_growth_cm', models.IntegerField(blank=True, null=True)),
                ('is_thorny', models.BooleanField(default=False)),
                ('leaf_shape', models.JSONField(blank=True, null=True)),
                ('flowering_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('flower_form', models.CharField(blank=True, max_length=100, null=True)),
                ('vegetation_periods', models.JSONField(default=list)),
                ('habit_forms', models.JSONField(default=list)),
                ('flower_colors', models.JSONField(blank=True, default=list, null=True)),
                ('leaf_colors', models.JSONField(blank=True, default=list, null=True)),
                ('flowering_months', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name': 'характеристики (вид)',
                'verbose_name_plural': 'характеристики (вид)',
                'db_table': 'plant_info"."plant_visual',
                'managed': False,
            },
        ),
    ]
