# Generated by Django 5.2.15 on 2026-06-05 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictCareLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'уровень ухода',
                'verbose_name_plural': 'уровни ухода',
                'db_table': 'plant_info"."dict_care_levels',
                'ordering': ['name'],
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DictDesigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'ландшафтный дизайнер',
                'verbose_name_plural': 'ландшафтные дизайнеры',
                'db_table': 'plant_info"."dict_designers',
                'ordering': ['name'],
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DictDesignUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'применение в дизайне',
                'verbose_name_plural': 'применение в дизайне',
                'db_table': 'plant_info"."dict_design_uses',
                'ordering': ['name'],
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DictFlowerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'форма цветка',
                'verbose_name_plural': 'формы цветка',
                'db_table': 'plant_info"."dict_flower_forms',
                'ordering': ['name'],
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DictFruitUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'практическое применение',
                'verbose_name_plural': 'практическое применение',
                'db_table': 'plant_info"."dict_fruit_uses',
                'ordering': ['name'],
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DictGardenStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'стиль сада',
                'verbose_name_plural': 'стили сада',
                'db_table': 'plant_info"."dict_garden_styles',
                'ordering': ['name'],
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DictHabitForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'жизненная форма',
                'verbose_name_plural': 'жизненные формы',
                'db_table': 'plant_info"."dict_habit_forms',
                'ordering': ['name'],
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DictLeafShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'форма листа',
                'verbose_name_plural': 'формы листа',
                'db_table': 'plant_info"."dict_leaf_shapes',
                'ordering': ['name'],
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DictPropagation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'способ размножения',
                'verbose_name_plural': 'способы размножения',
                'db_table': 'plant_info"."dict_propagation_methods',
                'ordering': ['name'],
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DictSoilAcidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'кислотность почвы',
                'verbose_name_plural': 'кислотность почвы',
                'db_table': 'plant_info"."dict_soil_acidity',
                'ordering': ['name'],
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DictSunType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'освещение',
                'verbose_name_plural': 'освещение',
                'db_table': 'plant_info"."dict_sun_types',
                'ordering': ['name'],
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantCareLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, related_name='care_levels', to='catalog.plant')),
                ('value', models.ForeignKey(db_column='care_level_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.dictcarelevel')),
            ],
            options={
                'db_table': 'plant_info"."plant_care_levels',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('plant', 'value'), name='uq_plant_care_level')],
            },
        ),
        migrations.CreateModel(
            name='PlantDesigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, related_name='designers', to='catalog.plant')),
                ('value', models.ForeignKey(db_column='designer_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.dictdesigner')),
            ],
            options={
                'db_table': 'plant_info"."plant_designers',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('plant', 'value'), name='uq_plant_designer')],
            },
        ),
        migrations.CreateModel(
            name='PlantDesignUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, related_name='design_uses_m2m', to='catalog.plant')),
                ('value', models.ForeignKey(db_column='design_use_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.dictdesignuse')),
            ],
            options={
                'db_table': 'plant_info"."plant_design_uses',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('plant', 'value'), name='uq_plant_design_use')],
            },
        ),
        migrations.CreateModel(
            name='PlantFlowerColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, related_name='flower_colors_m2m', to='catalog.plant')),
                ('value', models.ForeignKey(db_column='color_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.color')),
            ],
            options={
                'db_table': 'plant_info"."plant_flower_colors',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('plant', 'value'), name='uq_plant_flower_color')],
            },
        ),
        migrations.CreateModel(
            name='PlantFlowerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, related_name='flower_forms', to='catalog.plant')),
                ('value', models.ForeignKey(db_column='flower_form_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.dictflowerform')),
            ],
            options={
                'db_table': 'plant_info"."plant_flower_forms',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('plant', 'value'), name='uq_plant_flower_form')],
            },
        ),
        migrations.CreateModel(
            name='PlantFloweringMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, related_name='flowering_months_m2m', to='catalog.plant')),
                ('value', models.ForeignKey(db_column='month_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.month')),
            ],
            options={
                'db_table': 'plant_info"."plant_flowering_months',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('plant', 'value'), name='uq_plant_flowering_month')],
            },
        ),
        migrations.CreateModel(
            name='PlantFruitingMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, related_name='fruiting_months_m2m', to='catalog.plant')),
                ('value', models.ForeignKey(db_column='month_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.month')),
            ],
            options={
                'db_table': 'plant_info"."plant_fruiting_months',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('plant', 'value'), name='uq_plant_fruiting_month')],
            },
        ),
        migrations.CreateModel(
            name='PlantFruitUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, related_name='fruit_uses_m2m', to='catalog.plant')),
                ('value', models.ForeignKey(db_column='fruit_use_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.dictfruituse')),
            ],
            options={
                'db_table': 'plant_info"."plant_fruit_uses',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('plant', 'value'), name='uq_plant_fruit_use')],
            },
        ),
        migrations.CreateModel(
            name='PlantGardenStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, related_name='garden_styles_m2m', to='catalog.plant')),
                ('value', models.ForeignKey(db_column='garden_style_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.dictgardenstyle')),
            ],
            options={
                'db_table': 'plant_info"."plant_garden_styles',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('plant', 'value'), name='uq_plant_garden_style')],
            },
        ),
        migrations.CreateModel(
            name='PlantHabitForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, related_name='habit_forms', to='catalog.plant')),
                ('value', models.ForeignKey(db_column='habit_form_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.dicthabitform')),
            ],
            options={
                'db_table': 'plant_info"."plant_habit_forms',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('plant', 'value'), name='uq_plant_habit_form')],
            },
        ),
        migrations.CreateModel(
            name='PlantLeafColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, related_name='leaf_colors_m2m', to='catalog.plant')),
                ('value', models.ForeignKey(db_column='color_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.color')),
            ],
            options={
                'db_table': 'plant_info"."plant_leaf_colors',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('plant', 'value'), name='uq_plant_leaf_color')],
            },
        ),
        migrations.CreateModel(
            name='PlantLeafShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, related_name='leaf_shapes', to='catalog.plant')),
                ('value', models.ForeignKey(db_column='leaf_shape_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.dictleafshape')),
            ],
            options={
                'db_table': 'plant_info"."plant_leaf_shapes',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('plant', 'value'), name='uq_plant_leaf_shape')],
            },
        ),
        migrations.CreateModel(
            name='PlantPropagation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, related_name='propagation_methods', to='catalog.plant')),
                ('value', models.ForeignKey(db_column='propagation_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.dictpropagation')),
            ],
            options={
                'db_table': 'plant_info"."plant_propagation_methods',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('plant', 'value'), name='uq_plant_propagation')],
            },
        ),
        migrations.CreateModel(
            name='PlantSoilAcidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, related_name='soil_acidity', to='catalog.plant')),
                ('value', models.ForeignKey(db_column='soil_acidity_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.dictsoilacidity')),
            ],
            options={
                'db_table': 'plant_info"."plant_soil_acidity',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('plant', 'value'), name='uq_plant_soil_acidity')],
            },
        ),
        migrations.CreateModel(
            name='PlantSunType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, related_name='sun_types', to='catalog.plant')),
                ('value', models.ForeignKey(db_column='sun_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.dictsuntype')),
            ],
            options={
                'db_table': 'plant_info"."plant_sun_types',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('plant', 'value'), name='uq_plant_sun_type')],
            },
        ),
        migrations.CreateModel(
            name='PlantVegetationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, related_name='vegetation_periods_m2m', to='catalog.plant')),
                ('value', models.ForeignKey(db_column='month_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.month')),
            ],
            options={
                'db_table': 'plant_info"."plant_vegetation_periods',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('plant', 'value'), name='uq_plant_vegetation_period')],
            },
        ),
    ]
