# Generated by Django 5.2.15 on 2026-06-28 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_author_description_color_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name='color',
            table='plant_info"."dict_colors',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, default='', max_length=200, verbose_name='имя автора')),
                ('text', models.TextField(verbose_name='текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='оценка')),
                ('status', models.CharField(choices=[('pending', 'на модерации'), ('approved', 'одобрен'), ('rejected', 'отклонён')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.plant')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'db_table': 'plant_info"."reviews',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.TextField(blank=True, null=True)),
                ('public_url', models.TextField()),
                ('preview_url', models.TextField(blank=True, null=True)),
                ('selected_for_card', models.BooleanField(default=False, verbose_name='в карточку')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.review')),
            ],
            options={
                'verbose_name': 'фото отзыва',
                'verbose_name_plural': 'фото отзывов',
                'db_table': 'plant_info"."review_photos',
                'managed': True,
            },
        ),
    ]
