# Generated by Django 5.2.15 on 2026-06-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='соц-ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_provider',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='соц-провайдер'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('social_id', ''), _negated=True), fields=('social_provider', 'social_id'), name='uq_user_social_account'),
        ),
    ]
